input("what is your name?")
print ("hi {name} and welcome to your story.") 
("")
input("please pick a item:")
("")
input("please pick a continent")
("")
input("please pick a sport")
("")
input ("please pick a a type of weather")