name=input("what is your name?")
print (f"hi {name} and welcome to your story.") 
print("")
item=input("please pick a item:")
print("")
continent=input("please pick a continent")
print("")
sport=input("please pick a sport")
print("")
print(f"that is a great choice i love {sport} aswell")
print("")
weather=input ("please pick a a type of weather")
print("wow thats a crazy type of weather")
print("")
print(f"in the unique continent of {continent} it was a very {weather} day. and on that day there was a {sport} game and in the stands of that game there was a {item}. yay you have completed your story!! ")
print("")
print("what a great story")
print("__________             .__                          .___         __  .__    .__        ")
print("\____    /____    ____ |  |__     _____ _____     __| _/____   _/  |_|  |__ |__| ______")
print("/     /\__  \ _/ ___\|  |  \   /     \\__  \   / __ |/ __ \  \   __\  |  \|  |/  ___/")
print(" /     /_ / __ \\  \___|   Y  \ |  Y Y  \/ __ \_/ /_/ \  ___/   |  | |   Y  \  |\___ \ ")
print("/_______ (____  /\___  >___|  / |__|_|  (____  /\____ |\___  >  |__| |___|  /__/____  >")
print("       \/    \/     \/     \/        \/     \/      \/    \/             \/        \/ ")